.\" Manpage for crumbs
.\" Contact frank.asseg@objecthunter.net to correct errors and typos
.TH man 1 "23 July 2018" "1.0" "crumbs man page"

.SH NAME
crumbs \- a bookmarking system for shell commands

.SH SYNOPSIS
crumbs [options] <action> <args>

.SH DESCRIPTION
crumbs is a bookmarking system for shell commands, that allows a user to store commands under a given name in a file system hierarchy. Each crumb is stored in a dedicated file. If the name contains forward slashes i.e. '/', each character sequence before a slash is interpreted as a directory name.

.SH OPTIONS
\-h/\--help    Show the usage dialog and exit

.SH ACTIONS
list                       List the stored crumbs
.br
insert <name> <cmd>        Add a new crumb
.br
insert-exec <name> <cmd>   Execute a command and add a crumb if it returned successfully
.br
show <name>                Show a stored crumb
.br
exec <name>                Execute a crumb
.br
delete                     Delete a crumb

.SH EXAMPLES
.PP
1. Insert a crumb named 'foo/bar' in the sub directory 'foo':
.PP
.ti +4
.B crumbs insert foo/bar "ls -la"
.PP
2. Execute a crumb named 'foo/bar' that was previously added:
.PP
.ti +4
.B crumbs exec foo/bar

.SH FILES
/etc/crumb.conf is the crumbs configuration file

.SH BUGS
No known bugs.

.SH AUTHOR
Frank Asseg (frank.asseg@objecthunter.net)

.SH ORGANIZATION
FILIADATA Informationssysteme für den Handel GmbH,
.br
dm-drogerie markt GmbH + Co. KG
